package model

// AutoGenerated https://xuri.me/toml-to-go/

type Configs struct {
	App    App    `toml:"app"`
	Server Server `toml:"server"`
	Api    Api    `toml:"api"`
}
type App struct {
	Name string `toml:"name"`
	Env  string `toml:"env"`
}
type Api struct {
	Encrypt string `toml:"encrypt"`
	Rules   Rules  `toml:"rules"`
}

type Rules struct {
	Less    bool `toml:"less"`
	Eastern bool `toml:"eastern"`
	Western bool `toml:"western"`
	Abcd    bool `toml:"abcd"`
	Abc     bool `toml:"abc"`
	Dcba    bool `toml:"dcba"`
	Cba     bool `toml:"cba"`
	Two     bool `toml:"two"`
	RptAb   bool `toml:"rptab"`
	Abab    bool `toml:"abab"`
	Aaaa    bool `toml:"aaaa"`
	Aaa     bool `toml:"aaa"`
}

type HTTP struct {
	Port int `toml:"port"`
}
type Grpc struct {
	Port int `toml:"port"`
}
type Master struct {
	Addr string `toml:"addr"`
}
type Slaves struct {
	Addr []string `toml:"addr"`
}

type Default struct {
	DialTimeout int64  `toml:"dialTimeout"`
	IdleTimeout int64  `toml:"idleTimeout"`
	MaxActive   int    `toml:"maxActive"`
	MaxIdle     int    `toml:"maxIdle"`
	ReadTimeout int64  `toml:"readTimeout"`
	Master      Master `toml:"master"`
	Slaves      Slaves `toml:"slaves"`
}
type Redis struct {
	Default Default `toml:"default"`
}
type Server struct {
	HTTP  HTTP  `toml:"http"`
	Grpc  Grpc  `toml:"grpc"`
	Redis Redis `toml:"redis"`
}
