// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"number-sender/internal/app/workers"
	"number-sender/internal/pkg/calculate"
	"number-sender/internal/pkg/config"
	"number-sender/internal/pkg/limit"
	"number-sender/internal/pkg/redis"
)

// Injectors from wire.go:

func InitApp() error {
	loadConfigs := config.NewLoadConfigs()
	defaultRedis := redis.NewDefaultRedis(loadConfigs)
	workersWorkers := workers.NewWorkers()
	chains := calculate.NewChains(loadConfigs)
	options := limit.Options{
		Configs: loadConfigs,
	}
	limiter := limit.NewLimiter(options)
	serverOptions := Options{
		configs:         loadConfigs,
		defaultRedis:    defaultRedis,
		workersInstance: workersWorkers,
		chains:          chains,
		limiter:         limiter,
	}
	error2 := initApp(serverOptions)
	return error2
}
